import './globals.css'

export const metadata = {
  title: 'Nuria Anton Portofolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='scroll-smooth'>
      <head>
        <link rel="shortcut icon" href="/codeSlash.png" />
      </head>
      <body>{children}</body>
    </html>
  )
}
